baseURL: https://weixu94.github.io
languageCode: en-us
title: Wei XU
theme: PaperMod
pagination:
  pagerSize: 20

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: About
      url: /about/
      weight: 20
    # - identifier: research
    #   name: Research
    #   url: /research/
    #   weight: 20
    # - identifier: teaching
    #   name: Teaching
    #   url: /teaching/
    #   weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 100

params:
  description: "Wei XU's personal website"
  author: Wei XU
  social: true
  # googleAnalyticsID: ""
  DateFormat: "2006-01-02"
  defaultTheme: auto
  hideFooter: true
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  hideSummary: true
  hideAuthor: true
  ShowToc: true
  TocOpen: false
  disableScrollToTop: false
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: false
    title: Wei XU
    subtitle: "I am a PhD student in the Department of Economics 
      at Chinese University of Hong Kong.
      I received both my Bachelor and Master Degree from 
      Central University of Finance and Economics."
    # **In 2024/2025, I will be on the academic job market.**
    imageUrl: "/me.jpg"
    imageWidth: 160
    imageHeight: 160
    imageTitle: Wei XU
    buttons:
      - name: CV
        url: /CV_XW.pdf
      - name: Research
        url: /research/
      - name: Teaching
        url: /teaching/
      - name: Blog
        url: /blog/
      - name: Tags
        url: /tags/

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/weixu94"
    - name: "rss"
      url: "/index.xml/"
    - name: "email"
      url: mailto:weixu1026@gmail.com
  
  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Wei XU"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn 
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2

enableGitInfo: true

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    # - :git
    # - date
    # - publishDate
  publishDate:
    - publishDate
    - date
  expiryDate:
    - expiryDate
